@echo off
echo Merging System.Collections.Immutable into main assembly...
.\Build\ILMerge.exe /v4 /copyattrs /keyfile:DDCloud-Public.snk /internalize:Watt\bin\Debug\System.Collections.Immutable.dll /out:Stage\Watt.nupkg\lib\net45\DD.Cloud.WebApi.TemplateToolkit.dll Watt\bin\Debug\DD.Cloud.WebApi.TemplateToolkit.dll Watt\bin\Debug\System.Collections.Immutable.dll
echo Building NuGet package...
NuGet Pack NuGet\Watt.nuspec
